version: '3'
services:
  ton-id-gen:
    container_name: ton-id-gen
    image: ton-id-gen
    user: "$UID:$GID"
    volumes:
      - ./keyring:/keyring

  ton-proxy:
    container_name: ton-proxy
    image: ton-proxy
    env_file:
      - .env
    environment:
      SERVER_IP: localhost
      WEB_SERVER_IP: ton-site
      WEB_SERVER_PORT: 80
      ADNL_ADRESS: ${ADNL_ADRESS}
      LOG: /app/log/tonsite.log
      CONFIG: /app/global.config.json
    user: "$UID:$GID"
    volumes:
      - ./keyring:/keyring
      - ./log:/app/log
    networks:
      - ton-network

  ton-site:
      container_name: ton-site
      image: nginxdemos/hello
      ports:
        - '80:80'
      restart: unless-stopped
      networks:
        - ton-network

networks:
  ton-network:
    driver: bridge